import React from 'react';

const GrossGamingRevenue = () => {
  return (
    <div>
      
      <p><strong>Definition:</strong> Total Gross Gaming Revenue represents the cumulative revenue generated by the platform over time. It is the total amount wagered by users minus the total amount won.</p>
      <p><strong>Formula:</strong> GGR = Total SC Bet - Total SC Win</p>
      <p><strong>Example:</strong> If users placed bets totaling $12,000 and won $8,000:</p>
      <p><strong>Total GGR = 12,000 - 8,000 = $4,000</strong></p>

      <h5> YTD (Year-to-Date) Gross Gaming Revenue</h5>
      <p><strong>Definition:</strong> YTD GGR refers to the gross gaming revenue generated from January 1st of the current year up to the current date. This helps track yearly performance.</p>
      <p><strong>Formula:</strong> YTD GGR = Σ (SC Bets from Jan 1st to Present) - Σ (SC Wins from Jan 1st to Present)</p>
      <p><strong>Example:</strong> If total SC bets since Jan 1st are $20,000 and total SC wins are $14,000:</p>
      <p><strong>YTD GGR = 20,000 - 14,000 = $6,000</strong></p>

      <h5> Average Monthly Gross Gaming Revenue</h5>
      <p><strong>Definition:</strong> Average Monthly GGR represents the average GGR per month calculated from the start of the year up to and including the current month.It is calculated for the current calendar year, starting from January 1st to the present date.</p>
      <p><strong>Formula:</strong> Avg Monthly GGR = Total GGR from Jan 1st till today ÷ [No. of Months Passed + (No. of Days in Current Month ÷ Total Days in Month)]</p>
      <p><strong>Example:</strong> Let &apos;s say the GGR generated per month is:</p>
      <ul>
        <li>January - $1000</li>
        <li>February - $1500</li>
        <li>March - $2000</li>
        <li>April - $2500 (Let &apos;s say we are in the 15th of April)</li>
      </ul>
      <p><strong>Total GGR = 1000 + 1500 + 2000 + 2500 = $7000</strong></p>
      <p><strong>Note: Assuming it is the 15th of a 30-day month, if we are calculating the average when the current month is not complete, we use the following formula to account for the number of days in the current month. </strong></p>
      <p><strong>Avg Monthly GGR = Total GGR from Jan 1st to Today / [No. of Months Passed + (No. of Days Until Today / Total Days in Current Month)]</strong></p>
      <p>For example, if we are in the 15th of April and we have GGR totaling $7000 from January 1st to present, with 3 months completed (January, February, March), and the current month (April) having 30 days, we would calculate as:</p>

      <p><strong>Avg Monthly GGR = 7000 / [3 + (15 / 30)] = 7000 / 3.5 = $2000</strong></p>

      <h5> MTD (Month-to-Date) Gross Gaming Revenue</h5>
      <p><strong>Definition:</strong> MTD GGR reflects the gross gaming revenue generated from the start of the current month up to the present date.</p>
      <p><strong>Formula:</strong> MTD GGR = Σ (SC Bets from 1st of Month) - Σ (SC Wins from 1st of Month)</p>
      <p><strong>Example:</strong> If total bets in the current month are $4000 and wins are $2800:</p>
      <p><strong>MTD GGR = 4000 - 2800 = $1200</strong></p>

      <h5> Last 7 Days Gross Gaming Revenue</h5>
      <p><strong>Definition:</strong> Last 7 Days GGR represents revenue generated over the most recent 7-day period. This helps in tracking recent short-term performance.</p>
      <p><strong>Formula:</strong> Last 7 Days GGR = Σ (SC Bets over last 7 days) - Σ (SC Wins over last 7 days)</p>
      <p><strong>Example:</strong> If total bets over the last 7 days are $3500 and total wins are $2700:</p>
      <p><strong>Last 7 Days GGR = 3500 - 2700 = $800</strong></p>
    </div>
  );
};

export default GrossGamingRevenue;
