import React from 'react';

const NetGamingRevenue = () => {
  return (
    <div>
      
      <p><strong>Definition:</strong> Net Gaming Revenue (NGR) refers to the total revenue generated from gaming activities after deducting the costs associated with redemptions, sc balance and vault balances. NGR is an essential metric for evaluating the profitability of gaming operations.</p>
      <p><strong>Formula:</strong> NGR = Purchase Amount - (Approved Redemption + SC Balance + Vault SC Balance)</p>
      <p><strong>Example:</strong> If the user made a purchase of $1000, $150 approved redemption, $50 in SC balance, and $100 in Vault SC balance, the NGR would be:</p>
      <p><strong>NGR = 1000 - (150 + 50 + 100) = $700</strong></p>

      <h5> YTD (Year-to-Date) Net Gaming Revenue</h5>
      <p><strong>Definition:</strong> YTD (Year-to-Date) NGR refers to the total NGR calculated from the start of the current year up to the present date. It helps track the revenue generated so far in the current year after deductions.</p>
      <p><strong>Formula:</strong> YTD NGR = Σ (NGR for each transaction from the start of the year to today)</p>
      <p><strong>Example:</strong> If the user made purchases as follows, with the respective redemptions and balances:</p>
      <ul>
        <li>January - Purchase Amount $500,  Approved Redemption $50, SC Balance $30, Vault SC Balance $40</li>
        <li>February - Purchase Amount $600,  Approved Redemption $60, SC Balance $40, Vault SC Balance $50</li>
        <li>March - Purchase Amount $700,  Approved Redemption $70, SC Balance $60, Vault SC Balance $80</li>
      </ul>
      <p>The YTD NGR would be calculated by summing the NGR for each month:</p>
      <p><strong>YTD NGR = (500 - (50 + 30 + 40)) + (600 - (60 + 40 + 50)) + (700 - (70 + 60 + 80))</strong></p>

      <h5> Average Monthly Net Gaming Revenue</h5>
      <p><strong>Definition:</strong> Average Monthly NGR is the average amount of net gaming revenue generated by the user per month, calculated over the months up to and including the current month. This metric is useful for evaluating revenue trends and user behavior on a monthly basis.It is calculated for the current calendar year, starting from January 1st to the present date.</p>
      <p><strong>Formula:</strong> Average Monthly NGR = Σ (Monthly NGRs) ÷ Number of Months passed</p>
      <p><strong>Example:</strong> Suppose the user made purchases as follows:</p>
      <ul>
        <li>January: $380</li>
        <li>February: $450</li>
        <li>March: $490</li>
        <li>April :$420 (Let’s say we are in the 15th of April)</li>
      </ul>
      <p>We calculate the NGR for each month and then divide by the number of months:</p>
      <p><strong>Total NGR = 380 + 450 + 490 + 420 = $1740</strong></p>

      <p><strong>Note: Assuming it is the 15th of a 30-day month, if we are calculating the average when the current month is not complete, we use the following formula to account for the number of days in the current month.</strong></p>
      <p><strong>Avg Monthly Total NGR  = Total NGR from Jan 1st to Today / [No. of Months Passed + (No. of Days Until Today / Total Days in Current Month)]</strong></p>
      <p>For example, if we are in the 15th of April and we have NGR totaling $1740 from January 1st to present, with 3 months completed (January, February, March), and the current month (April) having 30 days, we would calculate as:</p>
      <p><strong>Avg Total Monthly NGR = 1740 / [3 + (15 / 30)]</strong></p>

      <h5> MTD (Month-to-Date) Net Gaming Revenue</h5>
      <p><strong>Definition:</strong> MTD (Month-to-Date) NGR refers to the total NGR generated by the user from the start of the current calendar month to the present date. It provides a snapshot of gaming revenue for the current month.</p>
      <p><strong>Formula:</strong> MTD NGR = Σ Purchase Amount - (Σ Approved Redemption + SC Balance + Vault SC Balance)</p>
      <p><strong>Example:</strong></p>
      <ul>
        <li>MTD Purchase Total = 400 + 500 = $900</li>
        <li>MTD Approved Redemption Total = 30 + 40 = $70</li>
        <li>SC Balance = $20 + $30 = $50</li>
        <li>Vault SC Balance = $25 + $40 = $65</li>
      </ul>
      <p><strong>MTD NGR = 900 - (70 + 50 + 65) = 900 - 185 = $715</strong></p>

      <h5> Last 7 Days Net Gaming Revenue</h5>
      <p><strong>Definition:</strong> Last 7 Days NGR refers to the total NGR generated by the user over the most recent 7-day period. This metric helps analyze short-term trends in revenue.</p>
      <p><strong>Formula:</strong> Last 7 Days NGR = Σ Purchase Amount - (Σ Approved Redemption + SC Balance + Vault SC Balance)</p>
      <p><strong>Example:</strong></p>
      <ul>
        <li>7-Day Purchase Total = 100 + 200 + 150 + 120 + 180 + 130 + 160 = $1040</li>
        <li>7-Day Approved Redemption Total = 10 + 30 + 20 + 15 + 25 + 18 + 22 = $140</li>
        <li>SC Balance Total = 5 + 15 + 10 + 8 + 12 + 9 + 11 = $70</li>
        <li>Vault SC Balance Total = 10 + 20 + 15 + 12 + 18 + 14 + 16 = $105</li>
      </ul>
      <p><strong>Last 7 Days NGR = 1040 - (140 + 70 + 105) = 1040 - 315 = $725</strong></p>
    </div>
  );
};

export default NetGamingRevenue;
