import React from 'react';

const TMFPlayerTierCriteria = () => {
  return (
    <div className="p-2 max-w-4xl mx-auto">


      <section className="mb-4">
       
        <p>
          The TMF User Rating Criteria is a structured and weighted scoring system developed to evaluate and classify
          casino players based on their profitability and behavioral patterns. Players are assigned to User Rating ranging
          from rating 0 (most profitable) to rating 5 (least desirable), allowing for strategic management of player
          engagement and business resources.
        </p>
        <p className="mt-2">
          <strong>Note:</strong> An override rule is applied to players with a Redemption-to-Deposit Ratio ≥ 95%,
          automatically classifying them into Rating 5, irrespective of other metrics.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Rating Definitions</h2>
        <table className="table-auto w-full border border-gray-300">
          <thead>
            <tr className="bg-gray-100">
              <th className="border px-4 py-2">Rating</th>
              <th className="border px-4 py-2">Score Range</th>
              <th className="border px-4 py-2">Description</th>
            </tr>
          </thead>
          <tbody>
            {[
              ['Rating 0', '4.1 - 5.0', 'Most profitable players. High engagement, low redemption, strong revenue contribution.'],
              ['Rating 1', '3.1 - 4.0', 'Highly profitable with minimal risk.'],
              ['Rating 2', '2.1 - 3.0', 'Moderately profitable. Balanced risk.'],
              ['Rating 3', '1.1 - 2.0', 'Lower profitability with moderate risk.'],
              ['Rating 4', '0.1 - 1.0', 'Low profit and higher risk behaviors.'],
              ['Rating 5', '0 or Redemption ≥ 95%', 'Least desirable. Typically bonus abusers or frequent withdrawers.']
            ].map(([Rating, score, desc], index) => (
              <tr key={index}>
                <td className="border px-4 py-2">{Rating}</td>
                <td className="border px-4 py-2">{score}</td>
                <td className="border px-4 py-2">{desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Scoring Methodology</h2>
        <p>
          Player evaluation is based on three weighted metrics unless the override condition is triggered. Each metric
          is scored from 0 to 5, where 5 is most favorable for the business. The weighted average of these scores
          determines the final Rating.
        </p>
        <h3 className="font-semibold mt-4">Override Rule</h3>
        <p><strong>Condition:</strong> Redemption-to-Deposit Ratio ≥ 95% (0.95 - 1.0)</p>
        <p><strong>Effect:</strong> Player is automatically placed in Rating 5</p>
        {/* <p><strong>Reason:</strong> High redemption ratio is a strong indicator of bonus abuse or risk behavior</p> */}
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Weighted Score Components</h2>
        <div className="mb-4">
          <h3 className="font-semibold">1. Lifetime Net Gross Revenue (NGR) - Weight: 50%</h3>
          <p><strong>Definition:</strong> Total revenue generated by the player over their lifetime, net of bonuses and operational costs.</p>
          <p><strong>Scoring:</strong></p>
          <ul className="list-disc ml-6">
            <li>$100,000+: 5</li>
            <li>$50,000 - $99,999: 4</li>
            <li>$25,000 - $49,999: 3</li>
            <li>$10,000 - $24,999: 2</li>
            <li>$5,000 - $9,999: 1</li>
            <li>$0-$4,999: 0</li>
          </ul>
        </div>
        <div className="mb-4">
          <h3 className="font-semibold">2. Redemption-to-Deposit Ratio - Weight: 30%</h3>
          <p><strong>Definition:</strong> Ratio of total redemptions to total deposits, scaled from 0 to 1.0 (0% to 100%).</p>
          <p><strong>Scoring:</strong></p>
          <ul className="list-disc ml-6">
            <li>0 - 0.2 (0%-20%): 5</li>
            <li>0.21 - 0.4 (21%-40%): 4</li>
            <li>0.41 - 0.6 (41%-60%): 3</li>
            <li>0.61 - 0.8 (61%-80%): 2</li>
            <li>0.81 - 0.94 (81%-94%): 1</li>
            <li>0.95 - 1.0 (95%-100%): Automatic Rating 5</li>
          </ul>
        </div>
        <div>
          <h3 className="font-semibold">3. Playthrough Amount - Weight: 20%</h3>
          <p><strong>Definition:</strong> Ratio of total bets (handle) to Lifetime NGR, expressed as a multiplier.</p>
          <p><strong>Scoring:</strong></p>
          <ul className="list-disc ml-6">
            <li>10x+: 5</li>
            <li>5x - 9.9x: 4</li>
            <li>3x - 4.9x: 3</li>
            <li>2x - 2.9x: 2</li>
            <li>1.1x - 1.9x: 1</li>
            <li>1x or less: 0</li>
          </ul>
        </div>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Final Score Calculation</h2>
        <p><strong>Formula (if Redemption &lt; 95%):</strong></p>
        <p>
          Total Score = (Lifetime NGR Score x 0.5) + (Redemption-to-Deposit Ratio Score x 0.3) + (Playthrough Amount Score x 0.2)
        </p>
        <p><strong>Range:</strong> 0 (worst) to 5 (best)</p>
        <p><strong>Override:</strong> If Redemption-to-Deposit Ratio ≥ 0.95, Rating 5 is assigned without calculation.</p>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Examples</h2>
        <div className="mb-4">
          <p><strong>Player A: High-Value Player</strong></p>
          <ul className="list-disc ml-6">
            <li>Lifetime NGR: $120,000 (Score: 5) → 50% x 5 = 2.5</li>
            <li>Redemption-to-Deposit Ratio: 0.15 (Score: 5) → 30% x 5 = 1.5</li>
            <li>Playthrough: 10x (Score: 5) → 20% x 5 = 1.0</li>
            <li>Total Score: 2.5 + 1.5 + 1.0 = 5.0 (Rating 0)</li>
          </ul>
        </div>
        <div className="mb-4">
          <p><strong>Player B: High Redemption Player</strong></p>
          <ul className="list-disc ml-6">
            <li>Lifetime NGR: $7,500 (Score: 1)</li>
            <li>Redemption-to-Deposit Ratio: 0.95 → Automatic Rating 5</li>
            <li>Playthrough: 1x (Score: 0)</li>
            <li>Result: Rating 5 due to override rule</li>
          </ul>
        </div>
        <div className="mb-4">
          <p><strong>Player C: Moderate Player</strong></p>
          <ul className="list-disc ml-6">
            <li>Lifetime NGR: $30,000 (Score: 3) → 50% x 3 = 1.5</li>
            <li>Redemption-to-Deposit Ratio: 0.5 (Score: 3) → 30% x 3 = 0.9</li>
            <li>Playthrough: 3x (Score: 3) → 20% x 3 = 0.6</li>
            <li>Total Score: 1.5 + 0.9 + 0.6 = 3.0 (Rating 2)</li>
          </ul>
        </div>
        <div>
          <p><strong>Player D: High NGR, High Redemption</strong></p>
          <ul className="list-disc ml-6">
            <li>Lifetime NGR: $150,000 (Score: 5)</li>
            <li>Redemption-to-Deposit Ratio: 1.0 → Automatic Rating 5</li>
            <li>Playthrough: 10x (Score: 5)</li>
            <li>Result: Rating 5 due to override rule</li>
          </ul>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">Implementation Notes</h2>
        <ul className="list-disc ml-6">
          <li><strong>Override Priority:</strong> Ensures immediate classification of high-risk players.</li>
          <li><strong>Purpose:</strong> Enables targeted player management, optimizing retention and operational resources.</li>
        </ul>
      </section>
    </div>
  );
};

export default TMFPlayerTierCriteria;
