// SOCKET RELATED

export const SOCKET_NAMESPACES = {
  WALLET: '/wallet',
  ACCOUNT_CAPTURE: '/accountCapture',
  LIVE_USER_COUNT: '/userCount',
  LEADER_BOARD: '/leader-board',
  ADMIN_NOTIFICATIONS: '/admin_notification',
  USER_NOTIFICATION: '/user-notification',
  JACKPOT_ADMIN: '/jackpot-admin'
}

export const SOCKET_EMITTERS = {
  USER_WALLET_BALANCE: 'USER_WALLET_BALANCE',
  ACCOUNT_CAPTURE: 'ACCOUNT_CAPTURE',
  USER_TRANSACTION: 'USER_USER_TRANSACTION',
  LIVE_USER_COUNT_LISTENER: 'LIVE_USER_COUNT',
  ADMIN_NOTIFICATIONS: 'ADMIN_NOTIFICATIONS',
  USER_NOTIFICATION_UPDATE: 'USER_NOTIFICATION_UPDATE',
  MAINTENANCE_MODE_UPDATE: 'MAINTENANCE_MODE_UPDATE',
  MULTI_LOGIN: 'MULTI_LOGIN',
  JACKPOT_ADMIN_UPDATE: 'JACKPOT_ADMIN_UPDATE'
}

export const SOCKET_LISTENERS = {
  USER_WALLET_BALANCE: SOCKET_NAMESPACES.WALLET + '/balance',
  ADMIN_NOTIFICATIONS: SOCKET_NAMESPACES.ADMIN_NOTIFICATIONS + '/admin-notification'
}
export const SOCKET_ROOMS = {
  USER_WALLET: 'USER_WALLET',
  ACCOUNT_CAPTURE: 'ACCOUNT_CAPTURE',
  LIVE_USERS: 'LIVE_USERS',
  LEADER_BOARD: 'LEADER_BOARD',
  ADMIN_NOTIFICATIONS: 'ADMIN_NOTIFICATIONS',
  USER_NOTIFICATION: 'USER_NOTIFICATION',
  MULTI_LOGIN: 'MULTI_LOGIN',
  KYC_STATUS: 'KYC_STATUS',
  JACKPOT: 'JACKPOT'
}
