import moment from "moment";
import { formatNumber } from "../../utils/helper";

export const tableHeaders = [
  { labelKey: 'user id', value: 'userId' },
  { labelKey: 'email', value: 'email' },
  { labelKey: 'username', value: 'username' },
  { labelKey: 'purchase', value: 'purchase' },
  { labelKey: 'redeem', value: 'redeem' },
  {labelKey: 'Pending Redeem Amount', value: 'totalPendingRedemptionAmount'},
  { labelKey: 'balance', value: 'balance' },
  { labelKey: 'play', value: 'play' },
  { labelKey: 'win', value: 'win' },
  { labelKey: 'ngr', value: 'NGR' },
  { labelKey: 'play through', value: 'playThrough' },
  { labelKey: 'ggr', value: 'GGR' },
  { labelKey: 'cancelled redemption count', value: 'cancelledRedemptionCount' },
  { labelKey: 'total redemption count', value: 'totalRedemptionCount' },
  { labelKey: 'purchase count', value: 'totalPurchaseCount' },
  { labelKey: 'pending redemption count', value: 'pendingRedemptionCount' },
  { labelKey: 'completed redemption count', value: 'completedRedemptionCount' },
  { labelKey: 'disabled user', value: 'disabledUser' },
  { labelKey: 'last login date', value: 'lastLoginDate' },
  { labelKey: 'registration date', value: 'registrationDate' },
  { labelKey: 'affiliate id', value: 'affiliateId' }
]

export const userDailyReportTableHeaders = [
  {labelKey :'Date', value:'date'},
  {labelKey:'Day', value:'dayName'},
  {labelKey:'Total SC Staked', value:'totalScStaked'},
  {labelKey:'Total SC Staked DOW Average', value:'totalScStakedDowAvg'},
  {labelKey:'Delta SC Staked', value:'deltaScStaked'},
  {labelKey:'7DMA Total SC Staked', value:'dma7TotalScStaked'},
  {labelKey:'30DMA Total SC Staked', value:'dma30TotalScStaked'},
  {labelKey:'Total GGR', value:'totalGgr'},
  {labelKey:'7DMA GGR', value:'dma7Ggr'},
  {labelKey:'30DMA GGR', value:'dma30Ggr'},
  {labelKey:'Total SC Awarded', value:'totalScAwarded'},
  {labelKey:'7DMA Total SC Awarded', value:'dma7TotalScAwarded'},
  {labelKey:'30DMA Total SC Awarded', value:'dma30TotalScAwarded'},
  {labelKey:'Total NGR (GGR - Bonus)', value:'totalNgr'},
  {labelKey:'7DMA Total NGR', value:'dma7TotalNgr'},
  {labelKey:'30DMA Total NGR', value:'dma30TotalNgr'},
  {labelKey:'Unique Logins', value:'uniqueLogins'},
  {labelKey:'DAU', value:'dau'},
  {labelKey:'ABPDAU', value:'abpdau'},
  {labelKey:'ABPDAU 7DMA',value:'dma7Abpdau'},
  {labelKey:'A(GGR)PDAU',value:'aggrPdau'},
  {labelKey:'7DMA A(GGR)PDAU',value:'dma7AggrPdau'},
  {labelKey:'30DMA A(GGR)PDAU',value:'dma30AggrPdau'},
  {labelKey:'A(NGR)PDAU',value:'angrPdau'},
  {labelKey:'7DMA A(NGR)PDAU',value:'dma7AngrPdau'},
  {labelKey:'30DMA A(NGR)PDAU',value:'dma30AngrPdau'},
  {labelKey:'Total Deposits',value:'totalDeposits'},
  {labelKey:'Avg Deposits on Day',value:'avgDepositsOnDay'},
  {labelKey:'Delta Deposits',value:'deltaDeposits'},
  {labelKey:'7DMA Deposits',value:'dma7Deposits'},
  {labelKey:'30DMA Deposits',value:'dma30Deposits'},
  {labelKey:'Depositors',value:'depositors'},
  {labelKey:'7DMA Depositors',value:'dma7Depositors'},
  {labelKey:'30DMA Depositors',value:'dma30Depositors'},
  {labelKey:'Withdrawal Requested',value:'withdrawalRequested'},
  {labelKey:'Withdrawal Completed',value:'withdrawalCompleted'},
  {labelKey:'New Registered Players',value:'newRegisteredPlayers'},
  {labelKey:'7DMA New Registered',value:'dma7NewRegistered'},
  {labelKey:'30DMA New Registered',value:'dma30NewRegistered'},
  {labelKey:'First Time Purchaser',value:'firstTimePurchasers'},
  {labelKey:'7DMA First Purchasers',value:'dma7FirstPurchasers'},
  {labelKey:'30DMA First Purchasers', value:'dma30FirstPurchasers'}
]

export const useAllColumnsDailyReport = () =>{

  return [
    {
      accessorKey: 'date',
      header: 'Date',
      enableResizing: true,
      cell: info => {
        const date = info.getValue();
        return date ? moment(date).format('MM/DD/YYYY') : 'NA';
      },
    },
    {
      accessorKey: 'dayName',
      header: 'Day',
      enableResizing: true,
      cell: info => info.getValue() || 'NA',
    },
    {
      accessorKey: 'totalScStaked',
      header: 'Total SC Staked',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'totalScStakedDowAvg',
      header: 'Total SC Staked DOW Average',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'deltaScStaked',
      header: 'Delta SC Staked',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7TotalScStaked',
      header: '7DMA Total SC Staked',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30TotalScStaked',
      header: '30DMA Total SC Staked',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'totalGgr',
      header: 'Total GGR',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7Ggr',
      header: '7DMA GGR',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30Ggr',
      header: '30DMA GGR',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'totalScAwarded',
      header: 'Total SC Awarded',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7TotalScAwarded',
      header: '7DMA Total SC Awarded',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30TotalScAwarded',
      header: '30DMA Total SC Awarded',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'totalNgr',
      header: 'Total NGR (GGR - Bonus)',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7TotalNgr',
      header: '7DMA Total NGR',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30TotalNgr',
      header: '30DMA Total NGR',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'uniqueLogins',
      header: 'Unique Logins',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'dau',
      header: 'DAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'abpdau',
      header: 'ABPDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7Abpdau',
      header: 'ABPDAU 7DMA',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'aggrPdau',
      header: 'A(GGR)PDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7AggrPdau',
      header: '7DMA A(GGR)PDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30AggrPdau',
      header: '30DMA A(GGR)PDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'angrPdau',
      header: 'A(NGR)PDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7AngrPdau',
      header: '7DMA A(NGR)PDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30AngrPdau',
      header: '30DMA A(NGR)PDAU',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'totalDeposits',
      header: 'Total Deposits',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'avgDepositsOnDay',
      header: 'Avg Deposits on Day',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'deltaDeposits',
      header: 'Delta Deposits',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma7Deposits',
      header: '7DMA Deposits',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30Deposits',
      header: '30DMA Deposits',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'depositors',
      header: 'Depositors',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'dma7Depositors',
      header: '7DMA Depositors',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30Depositors',
      header: '30DMA Depositors',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'withdrawalRequested',
      header: 'Withdrawal Requested',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'withdrawalCompleted',
      header: 'Withdrawal Completed',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'newRegisteredPlayers',
      header: 'New Registered Players',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'dma7NewRegistered',
      header: '7DMA New Registered',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30NewRegistered',
      header: '30DMA New Registered',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'firstTimePurchasers',
      header: 'First Time Purchaser',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: false }) ?? 'NA',
    },
    {
      accessorKey: 'dma7FirstPurchasers',
      header: '7DMA First Purchasers',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dma30FirstPurchasers',
      header: '30DMA First Purchasers',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'adminAddedScBonus',
      header: 'Admin Added Sc Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'affiliateBonus',
      header: 'Affiliate Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'amoeBonus',
      header: 'AMOE Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'crmPromocodeBonus',
      header: 'CRM Promocode Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'dailyBonus',
      header: 'Daily Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'freeSpinBonus',
      header: 'Free Spin Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'jackpotWinner',
      header: 'Jackpot Winner',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'monthlyTierBonus',
      header: 'Monthly Tier Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'packageBonus',
      header: 'Package Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'promotionBonus',
      header: 'Promotion Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'providerBonus',
      header: 'Provider Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'purchasePromocodeBonus',
      header: 'Purchase Promocode Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'rafflePayout',
      header: 'Raffle Payout',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'referralBonus',
      header: 'Referral Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'scratchCardBonus',
      header: 'Scratch Card Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'tierBonus',
      header: 'Tier Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'tournamentWinner',
      header: 'Tournament Winner',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'vipQuestionnaireBonus',
      header: 'VIP Questionnaire Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'weeklyTierBonus',
      header: 'Weekly Tier Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
    {
      accessorKey: 'welcomeBonus',
      header: 'Welcome Bonus',
      enableResizing: true,
      cell: info => formatNumber(info.getValue(), { isDecimal: true }) ?? 'NA',
    },
  ];

}
